# https://estafette.io/usage/manifest/
labels:
  container: npm-browser-agent
  team: frontend
  language: docker

version:
  semver:
    major: 0
    minor: 0

stages:
  bake:
    image: extensions/docker:stable
    action: build
    container: ${ESTAFETTE_LABEL_CONTAINER}
    repositories:
    - travix

  integration-test:
    image: eu.gcr.io/travix-com/${ESTAFETTE_LABEL_CONTAINER}:${ESTAFETTE_BUILD_VERSION}

  push-to-docker-registry-for-branch:
    image: extensions/docker:stable
    action: push
    container: ${ESTAFETTE_LABEL_CONTAINER}
    repositories:
    - travix
    tags:
    - ${ESTAFETTE_GIT_BRANCH}
    when:
      status == 'succeeded' &&
      branch != 'master'

  push-to-docker-registry-for-master:
    image: extensions/docker:stable
    action: push
    container: ${ESTAFETTE_LABEL_CONTAINER}
    repositories:
    - travix
    tags:
    - latest
    when:
      status == 'succeeded' &&
      branch == 'master'

  slack-notify:
    image: extensions/slack-build-status:stable
    workspace: travix
    channels:
    - '#builds-${ESTAFETTE_LABEL_TEAM}'
    when:
      status == 'failed'